// Complete Friends Episode Database
const episodes = [
  // Season 1
  { season: 1, episode: 1, title: "The One Where Monica Gets a Roommate" },
  { season: 1, episode: 2, title: "The One with the Sonogram at the End" },
  { season: 1, episode: 3, title: "The One with the Thumb" },
  { season: 1, episode: 4, title: "The One with George Stephanopoulos" },
  { season: 1, episode: 5, title: "The One with the East German Laundry Detergent" },
  { season: 1, episode: 6, title: "The One with the Butt" },
  { season: 1, episode: 7, title: "The One with the Blackout" },
  { season: 1, episode: 8, title: "The One Where Nana Dies Twice" },
  { season: 1, episode: 9, title: "The One Where Underdog Gets Away" },
  { season: 1, episode: 10, title: "The One with the Monkey" },
  { season: 1, episode: 11, title: "The One with Mrs. Bing" },
  { season: 1, episode: 12, title: "The One with the Dozen Lasagnas" },
  { season: 1, episode: 13, title: "The One with the Boobies" },
  { season: 1, episode: 14, title: "The One with the Candy Hearts" },
  { season: 1, episode: 15, title: "The One with the Stoned Guy" },
  { season: 1, episode: 16, title: "The One with Two Parts: Part 1" },
  { season: 1, episode: 17, title: "The One with Two Parts: Part 2" },
  { season: 1, episode: 18, title: "The One with All the Poker" },
  { season: 1, episode: 19, title: "The One Where the Monkey Gets Away" },
  { season: 1, episode: 20, title: "The One with the Evil Orthodontist" },
  { season: 1, episode: 21, title: "The One with the Fake Monica" },
  { season: 1, episode: 22, title: "The One with the Ick Factor" },
  { season: 1, episode: 23, title: "The One with the Birth" },
  { season: 1, episode: 24, title: "The One Where Rachel Finds Out" },

  // Season 2
  { season: 2, episode: 1, title: "The One with Ross's New Girlfriend" },
  { season: 2, episode: 2, title: "The One with the Breast Milk" },
  { season: 2, episode: 3, title: "The One Where Heckles Dies" },
  { season: 2, episode: 4, title: "The One with Phoebe's Husband" },
  { season: 2, episode: 5, title: "The One with Five Steaks and an Eggplant" },
  { season: 2, episode: 6, title: "The One with the Baby on the Bus" },
  { season: 2, episode: 7, title: "The One Where Ross Finds Out" },
  { season: 2, episode: 8, title: "The One with the List" },
  { season: 2, episode: 9, title: "The One with Phoebe's Dad" },
  { season: 2, episode: 10, title: "The One with Russ" },
  { season: 2, episode: 11, title: "The One with the Lesbian Wedding" },
  { season: 2, episode: 12, title: "The One After the Superbowl: Part 1" },
  { season: 2, episode: 13, title: "The One After the Superbowl: Part 2" },
  { season: 2, episode: 14, title: "The One with the Prom Video" },
  { season: 2, episode: 15, title: "The One Where Ross and Rachel...You Know" },
  { season: 2, episode: 16, title: "The One Where Joey Moves Out" },
  { season: 2, episode: 17, title: "The One Where Eddie Moves In" },
  { season: 2, episode: 18, title: "The One Where Dr. Ramoray Dies" },
  { season: 2, episode: 19, title: "The One Where Eddie Won't Go" },
  { season: 2, episode: 20, title: "The One Where Old Yeller Dies" },
  { season: 2, episode: 21, title: "The One with the Bullies" },
  { season: 2, episode: 22, title: "The One with Two Parties" },
  { season: 2, episode: 23, title: "The One with the Chicken Pox" },
  { season: 2, episode: 24, title: "The One with Barry and Mindy's Wedding" },

  // Season 3
  { season: 3, episode: 1, title: "The One with the Princess Leia Fantasy" },
  { season: 3, episode: 2, title: "The One Where No One's Ready" },
  { season: 3, episode: 3, title: "The One with the Jam" },
  { season: 3, episode: 4, title: "The One with the Metaphorical Tunnel" },
  { season: 3, episode: 5, title: "The One with Frank Jr." },
  { season: 3, episode: 6, title: "The One with the Flashback" },
  { season: 3, episode: 7, title: "The One with the Race Car Bed" },
  { season: 3, episode: 8, title: "The One with the Giant Poking Device" },
  { season: 3, episode: 9, title: "The One with the Football" },
  { season: 3, episode: 10, title: "The One Where Rachel Quits" },
  { season: 3, episode: 11, title: "The One Where Chandler Can't Remember Which Sister" },
  { season: 3, episode: 12, title: "The One with All the Jealousy" },
  { season: 3, episode: 13, title: "The One Where Monica and Richard Are Just Friends" },
  { season: 3, episode: 14, title: "The One with Phoebe's Ex-Partner" },
  { season: 3, episode: 15, title: "The One Where Ross and Rachel Take a Break" },
  { season: 3, episode: 16, title: "The One the Morning After" },
  { season: 3, episode: 17, title: "The One Without the Ski Trip" },
  { season: 3, episode: 18, title: "The One with the Hypnosis Tape" },
  { season: 3, episode: 19, title: "The One with the Tiny T-Shirt" },
  { season: 3, episode: 20, title: "The One with the Dollhouse" },
  { season: 3, episode: 21, title: "The One with a Chick and a Duck" },
  { season: 3, episode: 22, title: "The One with the Screamer" },
  { season: 3, episode: 23, title: "The One with Ross's Thing" },
  { season: 3, episode: 24, title: "The One with the Ultimate Fighting Champion" },
  { season: 3, episode: 25, title: "The One at the Beach" },

  // Season 4
  { season: 4, episode: 1, title: "The One with the Jellyfish" },
  { season: 4, episode: 2, title: "The One with the Cat" },
  { season: 4, episode: 3, title: "The One with the 'Cuffs" },
  { season: 4, episode: 4, title: "The One with the Ballroom Dancing" },
  { season: 4, episode: 5, title: "The One with Joey's New Girlfriend" },
  { season: 4, episode: 6, title: "The One with the Dirty Girl" },
  { season: 4, episode: 7, title: "The One Where Chandler Crosses the Line" },
  { season: 4, episode: 8, title: "The One with Chandler in a Box" },
  { season: 4, episode: 9, title: "The One Where They're Going to Party!" },
  { season: 4, episode: 10, title: "The One with the Girl from Poughkeepsie" },
  { season: 4, episode: 11, title: "The One with Phoebe's Uterus" },
  { season: 4, episode: 12, title: "The One with the Embryos" },
  { season: 4, episode: 13, title: "The One with Rachel's Crush" },
  { season: 4, episode: 14, title: "The One with Joey's Dirty Day" },
  { season: 4, episode: 15, title: "The One with All the Rugby" },
  { season: 4, episode: 16, title: "The One with the Fake Party" },
  { season: 4, episode: 17, title: "The One with the Free Porn" },
  { season: 4, episode: 18, title: "The One with Rachel's New Dress" },
  { season: 4, episode: 19, title: "The One with All the Haste" },
  { season: 4, episode: 20, title: "The One with All the Wedding Dresses" },
  { season: 4, episode: 21, title: "The One with the Invitation" },
  { season: 4, episode: 22, title: "The One with the Worst Best Man Ever" },
  { season: 4, episode: 23, title: "The One with Ross's Wedding: Part 1" },
  { season: 4, episode: 24, title: "The One with Ross's Wedding: Part 2" },

  // Season 5
  { season: 5, episode: 1, title: "The One After Ross Says Rachel" },
  { season: 5, episode: 2, title: "The One with All the Kissing" },
  { season: 5, episode: 3, title: "The One Hundredth" },
  { season: 5, episode: 4, title: "The One Where Phoebe Hates PBS" },
  { season: 5, episode: 5, title: "The One with the Kips" },
  { season: 5, episode: 6, title: "The One with the Yeti" },
  { season: 5, episode: 7, title: "The One Where Ross Moves In" },
  { season: 5, episode: 8, title: "The One with All the Thanksgivings" },
  { season: 5, episode: 9, title: "The One with Ross's Sandwich" },
  { season: 5, episode: 10, title: "The One with the Inappropriate Sister" },
  { season: 5, episode: 11, title: "The One with All the Resolutions" },
  { season: 5, episode: 12, title: "The One with Chandler's Work Laugh" },
  { season: 5, episode: 13, title: "The One with Joey's Bag" },
  { season: 5, episode: 14, title: "The One Where Everybody Finds Out" },
  { season: 5, episode: 15, title: "The One with the Girl Who Hits Joey" },
  { season: 5, episode: 16, title: "The One with the Cop" },
  { season: 5, episode: 17, title: "The One with Rachel's Inadvertent Kiss" },
  { season: 5, episode: 18, title: "The One Where Rachel Smokes" },
  { season: 5, episode: 19, title: "The One Where Ross Can't Flirt" },
  { season: 5, episode: 20, title: "The One with the Ride-Along" },
  { season: 5, episode: 21, title: "The One with the Ball" },
  { season: 5, episode: 22, title: "The One with Joey's Big Break" },
  { season: 5, episode: 23, title: "The One in Vegas: Part 1" },
  { season: 5, episode: 24, title: "The One in Vegas: Part 2" },

  // Season 6
  { season: 6, episode: 1, title: "The One After Vegas" },
  { season: 6, episode: 2, title: "The One Where Ross Hugs Rachel" },
  { season: 6, episode: 3, title: "The One with Ross's Denial" },
  { season: 6, episode: 4, title: "The One Where Joey Loses His Insurance" },
  { season: 6, episode: 5, title: "The One with Joey's Porsche" },
  { season: 6, episode: 6, title: "The One on the Last Night" },
  { season: 6, episode: 7, title: "The One Where Phoebe Runs" },
  { season: 6, episode: 8, title: "The One with Ross's Teeth" },
  { season: 6, episode: 9, title: "The One Where Ross Got High" },
  { season: 6, episode: 10, title: "The One with the Routine" },
  { season: 6, episode: 11, title: "The One with the Apothecary Table" },
  { season: 6, episode: 12, title: "The One with the Joke" },
  { season: 6, episode: 13, title: "The One with Rachels Sister" },
  { season: 6, episode: 14, title: "The One Where Chandler Can't Cry" },
  { season: 6, episode: 15, title: "The One That Could Have Been: Part 1" },
  { season: 6, episode: 16, title: "The One That Could Have Been: Part 2" },
  { season: 6, episode: 17, title: "The One with Unagi" },
  { season: 6, episode: 18, title: "The One Where Ross Dates a Student" },
  { season: 6, episode: 19, title: "The One with Joey's Fridge" },
  { season: 6, episode: 20, title: "The One with Mac and C.H.E.E.S.E." },
  { season: 6, episode: 21, title: "The One Where Ross Meets Elizabeth's Dad" },
  { season: 6, episode: 22, title: "The One Where Paul's the Man" },
  { season: 6, episode: 23, title: "The One with the Ring" },
  { season: 6, episode: 24, title: "The One with the Proposal: Part 1" },
  { season: 6, episode: 25, title: "The One with the Proposal: Part 2" },

  // Season 7
  { season: 7, episode: 1, title: "The One with Monica's Thunder" },
  { season: 7, episode: 2, title: "The One with Rachel's Book" },
  { season: 7, episode: 3, title: "The One with Phoebe's Cookies" },
  { season: 7, episode: 4, title: "The One with Rachel's Assistant" },
  { season: 7, episode: 5, title: "The One with the Engagement Picture" },
  { season: 7, episode: 6, title: "The One with the Nap Partners" },
  { season: 7, episode: 7, title: "The One with Ross's Library Book" },
  { season: 7, episode: 8, title: "The One Where Chandler Doesn't Like Dogs" },
  { season: 7, episode: 9, title: "The One with All the Candy" },
  { season: 7, episode: 10, title: "The One with the Holiday Armadillo" },
  { season: 7, episode: 11, title: "The One with All the Cheesecakes" },
  { season: 7, episode: 12, title: "The One Where They're Up All Night" },
  { season: 7, episode: 13, title: "The One Where Rosita Dies" },
  { season: 7, episode: 14, title: "The One Where They All Turn Thirty" },
  { season: 7, episode: 15, title: "The One with Joey's New Brain" },
  { season: 7, episode: 16, title: "The One with the Truth About London" },
  { season: 7, episode: 17, title: "The One with the Cheap Wedding Dress" },
  { season: 7, episode: 18, title: "The One with Joey's Award" },
  { season: 7, episode: 19, title: "The One with Ross and Monica's Cousin" },
  { season: 7, episode: 20, title: "The One with Rachel's Big Kiss" },
  { season: 7, episode: 21, title: "The One with the Vows" },
  { season: 7, episode: 22, title: "The One with Chandler's Dad" },
  { season: 7, episode: 23, title: "The One with Monica and Chandler's Wedding: Part 1" },
  { season: 7, episode: 24, title: "The One with Monica and Chandler's Wedding: Part 2" },

  // Season 8
  { season: 8, episode: 1, title: "The One After 'I Do'" },
  { season: 8, episode: 2, title: "The One with the Red Sweater" },
  { season: 8, episode: 3, title: "The One Where Rachel Tells..." },
  { season: 8, episode: 4, title: "The One with the Videotape" },
  { season: 8, episode: 5, title: "The One with Rachel's Date" },
  { season: 8, episode: 6, title: "The One with the Halloween Party" },
  { season: 8, episode: 7, title: "The One with the Stain" },
  { season: 8, episode: 8, title: "The One with the Stripper" },
  { season: 8, episode: 9, title: "The One with the Rumor" },
  { season: 8, episode: 10, title: "The One with Monica's Boots" },
  { season: 8, episode: 11, title: "The One with Ross's Step Forward" },
  { season: 8, episode: 12, title: "The One Where Joey Dates Rachel" },
  { season: 8, episode: 13, title: "The One Where Chandler Takes a Bath" },
  { season: 8, episode: 14, title: "The One with the Secret Closet" },
  { season: 8, episode: 15, title: "The One with the Birthing Video" },
  { season: 8, episode: 16, title: "The One Where Joey Tells Rachel" },
  { season: 8, episode: 17, title: "The One with the Tea Leaves" },
  { season: 8, episode: 18, title: "The One in Massapequa" },
  { season: 8, episode: 19, title: "The One with Joey's Interview" },
  { season: 8, episode: 20, title: "The One with the Baby Shower" },
  { season: 8, episode: 21, title: "The One with the Cooking Class" },
  { season: 8, episode: 22, title: "The One Where Rachel Is Late" },
  { season: 8, episode: 23, title: "The One Where Rachel Has a Baby: Part 1" },
  { season: 8, episode: 24, title: "The One Where Rachel Has a Baby: Part 2" },

  // Season 9
  { season: 9, episode: 1, title: "The One Where No One Proposes" },
  { season: 9, episode: 2, title: "The One Where Emma Cries" },
  { season: 9, episode: 3, title: "The One with the Pediatrician" },
  { season: 9, episode: 4, title: "The One with the Sharks" },
  { season: 9, episode: 5, title: "The One with Phoebe's Birthday Dinner" },
  { season: 9, episode: 6, title: "The One with the Male Nanny" },
  { season: 9, episode: 7, title: "The One with Ross's Inappropriate Song" },
  { season: 9, episode: 8, title: "The One with Rachel's Other Sister" },
  { season: 9, episode: 9, title: "The One with Rachel's Phone Number" },
  { season: 9, episode: 10, title: "The One with Christmas in Tulsa" },
  { season: 9, episode: 11, title: "The One Where Rachel Goes Back to Work" },
  { season: 9, episode: 12, title: "The One with Phoebe's Rats" },
  { season: 9, episode: 13, title: "The One Where Monica Sings" },
  { season: 9, episode: 14, title: "The One with the Blind Dates" },
  { season: 9, episode: 15, title: "The One with the Mugging" },
  { season: 9, episode: 16, title: "The One with the Boob Job" },
  { season: 9, episode: 17, title: "The One with the Memorial Service" },
  { season: 9, episode: 18, title: "The One with the Lottery" },
  { season: 9, episode: 19, title: "The One with Rachel's Dream" },
  { season: 9, episode: 20, title: "The One with the Soap Opera Party" },
  { season: 9, episode: 21, title: "The One with the Fertility Test" },
  { season: 9, episode: 22, title: "The One with the Donor" },
  { season: 9, episode: 23, title: "The One in Barbados: Part 1" },
  { season: 9, episode: 24, title: "The One in Barbados: Part 2" },

  // Season 10
  { season: 10, episode: 1, title: "The One After Joey and Rachel Kiss" },
  { season: 10, episode: 2, title: "The One Where Ross Is Fine" },
  { season: 10, episode: 3, title: "The One with Ross's Tan" },
  { season: 10, episode: 4, title: "The One with the Cake" },
  { season: 10, episode: 5, title: "The One Where Rachel's Sister Babysits" },
  { season: 10, episode: 6, title: "The One with Ross's Grant" },
  { season: 10, episode: 7, title: "The One with the Home Study" },
  { season: 10, episode: 8, title: "The One with the Late Thanksgiving" },
  { season: 10, episode: 9, title: "The One with the Birth Mother" },
  { season: 10, episode: 10, title: "The One Where Chandler Gets Caught" },
  { season: 10, episode: 11, title: "The One Where the Stripper Cries" },
  { season: 10, episode: 12, title: "The One with Phoebe's Wedding" },
  { season: 10, episode: 13, title: "The One Where Joey Speaks French" },
  { season: 10, episode: 14, title: "The One with Princess Consuela" },
  { season: 10, episode: 15, title: "The One Where Estelle Dies" },
  { season: 10, episode: 16, title: "The One with Rachel's Going Away Party" },
  { season: 10, episode: 17, title: "The Last One: Part 1" },
  { season: 10, episode: 18, title: "The Last One: Part 2" }
];
